flags: {}
packages:
- '.'
extra-deps:
- OneTuple-0.2.1
- gi-cairo-0.1.14.14
- gi-gdk-0.3.18.14
- gi-gdkpixbuf-0.2.32.14
- gi-gio-0.2.46.14
- gi-glib-0.2.46.14
- gi-gobject-0.2.46.14
- gi-pango-0.1.38.14
- haskell-gi-base-0.14
- suspend-0.2.0.0
- timers-0.2.0.3
- tuple-0.3.0.2
resolver: lts-5.17
